"""Add Review Model

Revision ID: 2ebd85269d6f
Revises: c88b624101d2
Create Date: 2024-01-05 09:44:07.574273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebd85269d6f'
down_revision = 'c88b624101d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
