"""Add Review Model

Revision ID: 7c1a5389693a
Revises: ee2c71bbdc86
Create Date: 2024-01-04 09:54:16.640973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1a5389693a'
down_revision = 'ee2c71bbdc86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
