"""Create Game Model

Revision ID: c88b624101d2
Revises: 7c1a5389693a
Create Date: 2024-01-05 09:43:32.286387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88b624101d2'
down_revision = '7c1a5389693a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
