"""Create Game Model

Revision ID: ee2c71bbdc86
Revises: 35ca1e9fbbe3
Create Date: 2024-01-04 09:52:58.020274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2c71bbdc86'
down_revision = '35ca1e9fbbe3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
